### ISSUE TITLE
Missing blocks

### ISSUE THREAD

**Issue by Joswon** [Moo-Ack-Productions/MCprep#557] opened 2024-04-08 18:58 UTC
When I open the import model tab, many blocks seem to be missing, including all the wools and cobblestone.

**Comment by StandingPadAnimations** [comment] 2024-04-08 19:55
Closing because this doesn't use the proper issue template (which we require to make sure we can get as much information as possible to reproduce the issue). Please open an issue using the Bug Report template (following all of the instructions listed) 
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/75058058/c2f9643e-0269-4db3-890d-d47d0736c30e)

**Closed by StandingPadAnimations** 2024-04-08 19:55 UTC
