### ISSUE TITLE
Command block texture is mashed when loaded

### ISSUE THREAD

**Issue by BBfiChe** [Moo-Ack-Productions/MCprep#488] opened 2023-10-01 02:31 UTC
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I see a mashed texture like in the screenshot attached below
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/113315299/e94427f8-47ba-4d20-a282-8eb65e92fe68)

### What steps are needed to produce the bug?

1). Open Blender
2). Place a command block with the place block in MCprep
3). If that doesn't work try the same steps again but after restarting blender.

### What version of MCprep are you using?

MCprep 3.5.0

### What version of Blender are you using?

Blender 3.6

**Comment by BBfiChe** [comment] 2023-10-01 02:38
Update:
This happenes with most full blocks that are placed manually into the world.
Non-full blocks like stairs are textured correctly just some full blocks are not.
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/113315299/700daa64-4e13-4a1d-a9a5-006298fdc69a)

**Comment by StandingPadAnimations** [comment] 2023-10-01 02:41
This looks like a resource pack issue. Are you using a custom resource pack?

**Comment by zNightlord** [comment] 2023-10-01 02:42
Some blocks like command block used animated textures so i guess that something prep material should handle also.

> Update: This happenes with most full blocks that are placed manually into the world. Non-full blocks like stairs are textured correctly just some full blocks are not. ![image](https://user-images.githubusercontent.com/113315299/271805188-700daa64-4e13-4a1d-a9a5-006298fdc69a.png)

May i asked? What block actually is this?

**Comment by StandingPadAnimations** [comment] 2023-10-01 02:47
> May i asked? What block actually is this?

Sea lantern. 

> Some blocks like command block used animated textures so i guess that something prep material should handle also.

According to the report, it's most full blocks that are affected, so animated textures doesn't explain anything here. I'll try and see what happens on my end, but I can't gurantee any help here (#481)

**Comment by zNightlord** [comment] 2023-10-01 02:59
They are so called "animated textures" unfortunately like prep material with lava.

https://raw.githubusercontent.com/InventivetalentDev/minecraft-assets/1.20.1/assets/minecraft/textures/block/command_block_front.png
https://raw.githubusercontent.com/InventivetalentDev/minecraft-assets/1.20.1/assets/minecraft/textures/block/sea_lantern.png

**Comment by StandingPadAnimations** [comment] 2023-10-01 03:04
Alright, so I've confirmed that some blocks are affected, but not all (planks for instance aren't).
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/75058058/fdabd30c-399f-4a5c-a02c-5c58430ec524)

Someone needs to do more digging into what blocks are affected, but I'll mark this as a bug

**Comment by StandingPadAnimations** [comment] 2023-10-01 03:06
In the meantime, try rescaling the UVs of the blocks generated (the gist is that the textures don't fit well on the UVs of the blocks in question) as a workaround

**Comment by zNightlord** [comment] 2023-10-01 03:07
Or also use the meshswap variant of command block and sea lantern. It is in there i think.

**Comment by TheDuckCow** [comment] 2023-10-01 06:03
Hey all, the answer here @BBfiChe is to tick on the box to "animate textures" when prepping materials on these objects, it should solve the issue and plus you'd then get some animations out of it. If you don't want it to be animated, you could always disable the animation part after the fact in the material editor.

So run "prep materials" with the object selected, then tick the box for Animate textures. Or directly use the "animate textures" button under advanced settings in the World Imports section of MCprep. Let us know if that solves your problem.

**Comment by BBfiChe** [comment] 2023-10-01 15:29
Okay. Thank you! I'll make sure that I check that next time!

**Comment by StandingPadAnimations** [comment] 2023-10-01 15:53
Assuming this is solved now, I'll close this report

**Closed by StandingPadAnimations** 2023-10-01 15:53 UTC
Labels: user-troubleshoot
