### ISSUE TITLE
Re-opening causes blocks and items/models to not load.

### ISSUE THREAD

**Issue by BBfiChe** [Moo-Ack-Productions/MCprep#486] opened 2023-09-27 02:55 UTC
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When trying to load my world into blender with MCprep, There seems to be an issue where my blocks, items and models to not load. It is only when I re-open a world when this happens. I don't know how to fix it and I think it may be a bug.

### What steps are needed to produce the bug?

1. Create a new animation in blender,
2. Create add some animations,
3. Export an animation,
4. Close Blender
5. Re-open blender and re-open the same .blend file
6. When trying to add an item or a block/model it won't load them and pressing reload does not work.

I have attached the image below. (Again I have tried to reload assets and it won't work so I don't know what to do.)
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/113315299/3ad7acc2-b1d9-4a7a-9080-6f29637397e4)

Here are some screenshots of what I see when trying to load them.
If this is not a bug but I may have done something wrong I'm sorry that I have wasted your time but would appreciate if you could respond to this and help me fix the issue. Thank you!

### What version of MCprep are you using?

MCprep 3.4.3

### What version of Blender are you using?

Blender 3.6

**Comment by StandingPadAnimations** [comment] 2023-09-28 17:40
> 1. Create a new animation in blender,
> 2. Create add some animations,
> 3. Export an animation,

That's not minimal enough to reproduce the issue on our end, can you try recreating the issue in a new file as minimal as possible?

So far I'm trying to reproduce the problem mentioned here, and it doesn't occur on my system.

**Comment by zNightlord** [comment] 2023-09-30 06:24
It would be the same for me.
But based on the images I can suspect what did you do to the advanced section's filepaths of the texturepack and maybe "clog" it in someway. 
Under the Advanced there is that revert arrow button use that to change back to what the MCprep default resourcepack

**Comment by StandingPadAnimations** [comment] 2024-01-07 00:42
Closing since the bug can't be reproduced. Feel free to comment on here if the bug still persists,

**Closed by StandingPadAnimations** 2024-01-07 00:42 UTC
Labels: user-troubleshoot
