### ISSUE TITLE
Map Block -> Top Down Render

### ISSUE THREAD

**Issue by Zachadactyl** [Moo-Ack-Productions/MCprep#470] opened 2023-08-25 18:34 UTC
### Check against existing requests

- [X] I have checked existing feature requests, and my idea is different

### Describe the context

Maps in Minecraft show a top down view of the world, but when imported into Blender (3.6.2) it is all grey and stretched.  What would be nice is to have a button to "revamp maps" and take a top down shot.  

### How do you imagine your feature works?

Perhaps in Prep Materials there would be a "change map" button.  When clicked, a camera would be added into the scene (as well as a top down sun) to match the correct rotation of the OBJ world, zoom to a fixed distance (basic maps are 64x64, no?) and render an image.png that would then be applied to the plane that is the map.  

### What existing workaround (or closest thing to a workaround) do you have today (within Blender, MCprep, or any software)? If there is no workaround, explain why you feel this way.

Currently I do the same as above, import a camera and sun (pointing down, or with faint shadows) line up the shot rotated the correct way, render it, apply it to the plane, and adjust specular, opacity, and roughness till I get a close look.  This looks 100x nicer than jmc2obj imports.  (Mineways doesn't import maps).

**Comment by zNightlord** [comment] 2023-08-25 19:02
The last part is quite a bit much because Minecraft map top view is a really flat (emission) color you can render the viewport solid mode/ Workbench renderer in a Flat color way, no pbr, sun import snarios like you mentioned. Also the camera resolution is really small like 64, it should be harder to know the shading effected there.

It would be another great extension of the panorama render. 
https://github.com/Moo-Ack-Productions/MCprep/pull/314

**Comment by StandingPadAnimations** [comment] 2023-08-25 21:21
I'm not sure about implementing this. On one hand, this would be useful. On the other, the problem to solve here is caused on the world exporter side, not MCprep. MCprep could approximate, but users would then expect us to recreate maps completely, with markers and whatnot. 

For now I'll close this (you'll still be able to comment), not because the suggestion is bad, but because the core problem is world exporter side. I suggest reporting this to the bug tracker your world exporter uses (with this issue linked for context reasons), and see what they say. 
- https://github.com/erich666/Mineways
- https://github.com/jmc2obj/j-mc-2-obj

Ultimately, world exporters know all when it comes to Minecraft worlds, MCprep just uses the info they choose to export. If the issue is unsolveable on the world exporter side, then I'll reopen this.

**Closed by StandingPadAnimations** 2023-08-25 21:21 UTC
Labels: enhancement
