### ISSUE TITLE
Missing blocks

### ISSUE THREAD

**Issue by Joswon** [Moo-Ack-Productions/MCprep#558] opened 2024-04-09 17:33 UTC
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When I open the Block spawner tab, most of the blocks are missing...
![Screenshot 2024-04-09 183235](https://github.com/Moo-Ack-Productions/MCprep/assets/146258656/f80cf7a8-d7c3-4dfc-a98f-68bbf7bf6bb7)

### What steps are needed to produce the bug?

I don't know

### What version of MCprep are you using?

The newest.

### What version of Blender are you using?

Newest version

**Comment by zNightlord** [comment] 2024-04-09 17:39
What steps are needed to produce the bug?
- Did you change the resource pack for texture swap or use texture swap? [Y/N]
- Did you change anything in the addon script folder or move the MCprep resourcepack there?
Type in "Cobble" in the Block Model spawner

**Comment by StandingPadAnimations** [comment] 2024-04-09 22:55
Like your previous report in #557, this report has problems. Sure, you may have used the template, but you also ignored the template instructions for the most important parts.

Some comments:
- “I don't know” isn't an accepted response for bug reports, because it provides no info on reproducing the bug. To quote #322 (which explains why we require using the template):
	> Steps to reproduce: this is by far the most important (along with screenshots). If the reported issue does indeed turn out to be a bug, we need to know how to reproduce the bug so fixing it becomes less of a pain 
	
	We MCprep developers are human, we can't magically remote into your machine and figure out what's causing your issue, we need proper steps to reproduce this in a new file so we can determine if A. this is a bug and B. if it is, where in the code is causing this bug. As it stands, it could either be a bug, user error, something in a specific file, etc, and we'd have no way to check without steps to reproduce.
- Regarding the following:
	> ### What steps are needed to produce the bug?
	> I don't know
	> 
	> ### What version of MCprep are you using?
	> The newest.
	> 
	> ### What version of Blender are you using?
	> Newest version
	
	This again doesn't follow the template. The template states to specify the version number, as seen below:
	![image](https://github.com/Moo-Ack-Productions/MCprep/assets/75058058/6794eeca-32d0-496d-aeef-916c208f8569)
	Saying “newest” may make sense at the moment, but what happens when MCprep 3.6 comes out? Or MCprep 4.0? This becomes confusing to anyone reading this in the future, as they'll have to dive and figure out what the newest versions of MCprep and Blender were at the time this was opened, and that's a waste of time.

	
Due to those problems, I'm also going to close this. You will still be able to comment, but I'm not going to reopen it.

**Closed by StandingPadAnimations** 2024-04-09 22:55 UTC
Labels: user-troubleshoot
