### ISSUE TITLE
Enderman Rig Has An Issue When Blinking

### ISSUE THREAD

**Issue by Sirocco745** [Moo-Ack-Productions/MCprep#542] opened 2024-02-12 02:00 UTC
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I was fiddling around with the different rigs once again when I noticed that the Enderman doesn't blink correctly when viewed in the textured or rendered viewport (both with Eevee and Cycles).
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/101165864/6fd9af4e-d2cb-47f4-ada9-922175412541)
I checked out the mesh and it looks like the head has some weird mesh mixup, where the wrong geometry has been keyed to the blink's driver and thus moves the wrong part of the eye. I think the reason this wasn't picked up during the creation of the rig would be because the eyes look fine when viewed in solid mode because of this geometry muck-up.
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/101165864/e7db1e7e-101f-4a9b-886b-b2c856375e53)

### What steps are needed to produce the bug?

1) Spawn in the Enderman preset rig
2) Make sure you are in the textured viewport
3) Go into pose mode and just fiddle around with the blink slider while looking at the eyes, you'll immediately see it

### What version of MCprep are you using?

MCprep 3.5.3

### What version of Blender are you using?

Blender 4.0

**Comment by StandingPadAnimations** [comment] 2024-02-12 02:58
I'll just add this as a known issue but not a bug. Rigs in MCprep aren't maintained by us, they're submitted and maintained by the community. If you want, you can submit a replacement

**Comment by Sirocco745** [comment] 2024-02-12 03:02
I FOUND A SOLUTION:
I was scrolling through some older issues and I found #188, in which the solution remains the same: when you spawn the rig, make sure to uncheck the prep materials box.
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/101165864/0377e392-e434-446d-9395-7723651a7ac8)

While I'm here, I might as well list all of the mobs that have texturing issues that are fixed by turning this setting **off**:
Evoker, Ghast, Hoglin, Horse, Husk, Iron Golem, Silverfish, Piglin, Vmcomix, Vindicator, Wandering Trader, Warden, Witch, and the Zombie Pigman.

**Comment by StandingPadAnimations** [comment] 2024-02-12 03:05
Again, we don't maintain rigs, they're community maintained. Those rigs come from BSS, who no longer maintain their rigs (frankly, they've disappeared off the earth as far as we can tell). I'll close this since the issue is resolved.

**Comment by Sirocco745** [comment] 2024-02-12 03:05
> I'll just add this as a known issue but not a bug. Rigs in MCprep aren't maintained by us, they're submitted and maintained by the community. If you want, you can submit a replacement

Ah, alright! That's my bad. I'm not well versed in coding or rigging myself yet, I just use this plugin because it's by far the best for what it does. Love all the work you guys put into this and will definitely contribute some stuff on the rigging side! Once I'm done with school, only got about 8 more months of soul-crushing study lmao

**Closed by StandingPadAnimations** 2024-02-12 03:05 UTC
Labels: Known issue

**Comment by zNightlord** [comment] 2024-02-12 03:18
> > I'll just add this as a known issue but not a bug. Rigs in MCprep aren't maintained by us, they're submitted and maintained by the community. If you want, you can submit a replacement
> 
> Ah, alright! That's my bad. I'm not well versed in coding or rigging myself yet, I just use this plugin because it's by far the best for what it does. Love all the work you guys put into this and will definitely contribute some stuff on the rigging side! Once I'm done with school, only got about 8 more months of soul-crushing study lmao

Thanks for the list of mobs also. Yes it is known issue with MCprep prep material "compatibility" with rigs have material setups, some already has that skipped/ turn off prep material when spawning already *(You can find this in the mcprep_data.json if you want to add those in)* 

It is like prep material decided to clean the material, so to me it isn't the rig side problem.

**Comment by Sirocco745** [comment] 2024-02-12 03:32
> Thanks for the list of mobs also. Yes it is known issue with MCprep prep material "compatibility" with rigs have material setups, some already has that skipped/ turn off prep material when spawning already _(You can find this in the mcprep_data.json if you want to add those in)_
> 
> It is like prep material decided to clean the material, so to me it isn't the rig side problem.

Thanks for letting me know what the right file is, lemme fiddle around with that and try to fix it!
