### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by umutbabapro234** [Moo-Ack-Productions/MCprep#581] opened 2024-05-21 15:19 UTC
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Hello I get this error when I want to activate 
Please help me.

### What steps are needed to produce the bug?

I zip and install the mcprep file and then I get this error when I want to activate it

### What version of MCprep are you using?

3.5.0

### What version of Blender are you using?

4.1

**Comment by umutbabapro234** [comment] 2024-05-21 15:19
![image](https://github.com/Moo-Ack-Productions/MCprep/assets/170444424/f63dc4d7-9bd5-4812-9d1f-99a39c3cf194)

**Comment by StandingPadAnimations** [comment] 2024-05-21 15:36
3.5.3 is the latest release of MCprep. Try that and see what happens

**Comment by TheDuckCow** [comment] 2024-06-19 19:16
Just checking @umutbabapro234 did the above suggestion work, or even just restarting blender? You could also try using the version of blender not shipped with Steam to see if that makes a difference, we don't test against that version as often though it has worked in the past, so I'd be surprised if this fundamental level of an issue was the cause.

**Comment by StandingPadAnimations** [comment] 2024-06-19 21:31
I'm going to close this simply because this isn't reproduceable on our end, but feel free to comment any extra details

**Closed by StandingPadAnimations** 2024-06-19 21:31 UTC
Labels: user-troubleshoot
